version: '3.7'

services:
  model_services:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python3", "main.py"]
    volumes:
      - ./weights/huggingface:/root/.cached/huggingface
    ports: 
      - 8000:8000
